#!/usr/bin/env bash

# Run identity and immutable initial center.
BASE_MODEL=${BASE_MODEL:-Qwen/Qwen3-4B-Base}
BASE_REVISION=${BASE_REVISION:-}
MODEL_ABBR=${MODEL_ABBR:-qwen3_4b}
# Formal run identity. Keep it literal so an exported smoke-test RUN_NAME
# cannot silently redirect this configuration into an existing run directory.
RUN_NAME=qwen3_4b_gaussian_kq16_ks6_sq0p001_ss0p001_b4000_vb32_seed42_r5
NUM_ROUNDS=${NUM_ROUNDS:-5}

# Formal-run population choices. Edit this file for a different experiment;
# these values intentionally do not inherit exported shell variables.
QUESTIONER_POPULATION_SIZE=16
SOLVER_POPULATION_SIZE=6
QUESTIONER_NOISE_SIGMA=0.001
SOLVER_NOISE_SIGMA=0.001
POPULATION_SEED=${POPULATION_SEED:-42}
TENSOR_PARALLEL_SIZE=${TENSOR_PARALLEL_SIZE:-1}

# Fixed standard-R-Zero budgets (the original formal run is 1000 attempts x 4 shards).
QUESTION_TOTAL_BUDGET=${QUESTION_TOTAL_BUDGET:-4000}
SOLVER_EXPERT_SAMPLES=${SOLVER_EXPERT_SAMPLES:-10}
SOLVER_LABEL_SAMPLES=${SOLVER_LABEL_SAMPLES:-9}

# Four-GPU stage layout. Logical population size is independent of these counts.
QUESTIONER_TRAIN_GPU_IDS=${QUESTIONER_TRAIN_GPU_IDS:-0,1}
SOLVER_EXPERT_GPU_IDS=${SOLVER_EXPERT_GPU_IDS:-2,3}
QUESTION_GENERATION_GPU_IDS=${QUESTION_GENERATION_GPU_IDS:-0,1,2,3}
SOLVER_EXPERT_PORT_BASE=${SOLVER_EXPERT_PORT_BASE:-5000}

# Center Questioner: standard R-Zero settings.
QUESTIONER_MAX_STEPS=${QUESTIONER_MAX_STEPS:-6}
QUESTIONER_MERGE_STEP=${QUESTIONER_MERGE_STEP:-5}
QUESTIONER_SAVE_FREQ=${QUESTIONER_SAVE_FREQ:-5}
QUESTIONER_ROLLOUT_BATCH_SIZE=${QUESTIONER_ROLLOUT_BATCH_SIZE:-512}
QUESTIONER_ROLLOUT_N=${QUESTIONER_ROLLOUT_N:-4}
QUESTIONER_GLOBAL_BATCH_SIZE=${QUESTIONER_GLOBAL_BATCH_SIZE:-4}
QUESTIONER_MICRO_BATCH_UPDATE=${QUESTIONER_MICRO_BATCH_UPDATE:-2}
QUESTIONER_MICRO_BATCH_EXPERIENCE=${QUESTIONER_MICRO_BATCH_EXPERIENCE:-8}
QUESTIONER_MAX_RESPONSE_LENGTH=${QUESTIONER_MAX_RESPONSE_LENGTH:-4096}
QUESTIONER_LOGGER=${QUESTIONER_LOGGER:-'["console","wandb"]'}

# Central Solver: standard R-Zero settings and selected step 15.
SOLVER_MAX_RESPONSE_LENGTH=${SOLVER_MAX_RESPONSE_LENGTH:-4096}
SOLVER_TOTAL_EPOCHS=${SOLVER_TOTAL_EPOCHS:-100}
SOLVER_MAX_STEPS=${SOLVER_MAX_STEPS:-20}
SOLVER_ROLLOUT_BATCH_SIZE=${SOLVER_ROLLOUT_BATCH_SIZE:-512}
SOLVER_ROLLOUT_N=${SOLVER_ROLLOUT_N:-5}
SOLVER_GLOBAL_BATCH_SIZE=${SOLVER_GLOBAL_BATCH_SIZE:-128}
SOLVER_VAL_FREQ=${SOLVER_VAL_FREQ:-4}
SOLVER_MERGE_STEP=${SOLVER_MERGE_STEP:-15}
SOLVER_SAVE_FREQ=${SOLVER_SAVE_FREQ:-5}
SOLVER_SAVE_LIMIT=${SOLVER_SAVE_LIMIT:-3}
SOLVER_LOGGER=${SOLVER_LOGGER:-'["console","wandb"]'}
DATASET_MIN_SCORE=${DATASET_MIN_SCORE:-0.3}
DATASET_MAX_SCORE=${DATASET_MAX_SCORE:-0.8}

# Runtime, storage, and optional evaluation.
STORAGE_PATH=${STORAGE_PATH:-/data/jinyuan/rzero_storage}
EVALUATE_EACH_ROUND=${EVALUATE_EACH_ROUND:-true}
FULL_LOAD_VALIDATE=${FULL_LOAD_VALIDATE:-false}
SOLVER_EXPERT_GPU_MEMORY_UTILIZATION=${SOLVER_EXPERT_GPU_MEMORY_UTILIZATION:-0.8}
QUESTION_GENERATION_GPU_MEMORY_UTILIZATION=${QUESTION_GENERATION_GPU_MEMORY_UTILIZATION:-0.8}
SOLVER_LABEL_GPU_MEMORY_UTILIZATION=${SOLVER_LABEL_GPU_MEMORY_UTILIZATION:-0.85}
SOLVER_EXPERT_MAX_TOKENS=${SOLVER_EXPERT_MAX_TOKENS:-4096}
QUESTION_GENERATION_MAX_TOKENS=${QUESTION_GENERATION_MAX_TOKENS:-4096}
SOLVER_LABEL_MAX_TOKENS=${SOLVER_LABEL_MAX_TOKENS:-4096}
SOLVER_LABEL_BATCH_SIZE=${SOLVER_LABEL_BATCH_SIZE:-0}
# Match the original R-Zero Solver-feedback service: bound the prompt count in
# each vLLM generate() call while the Questioner is being trained.
VLLM_SERVER_BATCH_SIZE=32
CENTER_ROLLOUT_TENSOR_PARALLEL_SIZE=${CENTER_ROLLOUT_TENSOR_PARALLEL_SIZE:-2}
