#!/usr/bin/env bash

# Required run identity and immutable Base.
BASE_MODEL=${BASE_MODEL:-Qwen/Qwen3-4B-Base}
BASE_REVISION=${BASE_REVISION:-}
MODEL_ABBR=${MODEL_ABBR:-qwen3_4b}
TASK_VECTOR_METHOD=${TASK_VECTOR_METHOD:-full}
if [ -z "${RUN_NAME:-}" ]; then
    if [ "$TASK_VECTOR_METHOD" = "relex_rank1" ]; then
        RUN_NAME="${MODEL_ABBR}_${RUN_VARIANT_SUFFIX:-relex_rank1}"
    else
        RUN_NAME="${MODEL_ABBR}_${RUN_VARIANT_SUFFIX:-full_delta}"
    fi
fi
NUM_ROUNDS=${NUM_ROUNDS:-5}
TASK_VECTOR_SCALES=(1 1 1 1 1)

# Storage and Hugging Face. STORAGE_PATH may be exported by env_rzero.sh.
STORAGE_PATH=${STORAGE_PATH:-/data/jinyuan/rzero_storage}
HUGGINGFACENAME=${HUGGINGFACENAME:-jinyuan222}
MIRROR_DATASETS=${MIRROR_DATASETS:-true}
UPLOAD_MODELS=${UPLOAD_MODELS:-false}
HF_MODELS_PRIVATE=${HF_MODELS_PRIVATE:-true}

# Reuse the original R-Zero round-1 Questioner and its already labeled/filtered
# Solver1 dataset. Both Full-delta and Rank-1 therefore start from exactly the
# same Q1/D1; the task-vector experiment begins at Base-fit Solver1 training.
BOOTSTRAP_ROUND1=${BOOTSTRAP_ROUND1:-true}
BOOTSTRAP_QUESTIONER_MODEL=${BOOTSTRAP_QUESTIONER_MODEL:-jinyuan222/qwen3_4b_fullrun_authorsettings_questioner_v1}
BOOTSTRAP_QUESTIONER_REVISION=${BOOTSTRAP_QUESTIONER_REVISION:-}
BOOTSTRAP_QUESTIONER_SUBPATH=${BOOTSTRAP_QUESTIONER_SUBPATH:-global_step_5/actor/huggingface}
BOOTSTRAP_DATASET=${BOOTSTRAP_DATASET:-jinyuan222/qwen3_4b_fullrun_authorsettings_solver_v1}
BOOTSTRAP_DATASET_CONFIG=${BOOTSTRAP_DATASET_CONFIG:-qwen3_4b_fullrun_authorsettings_solver_v1}
BOOTSTRAP_DATASET_SPLIT=${BOOTSTRAP_DATASET_SPLIT:-train}
BOOTSTRAP_DATASET_REVISION=${BOOTSTRAP_DATASET_REVISION:-}

# Evaluation can be disabled for smoke tests without changing training.
EVALUATE_EACH_ROUND=${EVALUATE_EACH_ROUND:-true}

# Questioner: defaults match the current R-Zero scripts.
QUESTIONER_TRAIN_GPU_IDS=${QUESTIONER_TRAIN_GPU_IDS:-0,1}
VLLM_GPU_IDS=${VLLM_GPU_IDS:-2,3}
VLLM_PORT_BASE=${VLLM_PORT_BASE:-5000}
QUESTIONER_MAX_STEPS=${QUESTIONER_MAX_STEPS:-6}
QUESTIONER_MERGE_STEP=${QUESTIONER_MERGE_STEP:-5}
QUESTIONER_SAVE_FREQ=${QUESTIONER_SAVE_FREQ:-5}
QUESTIONER_ROLLOUT_BATCH_SIZE=${QUESTIONER_ROLLOUT_BATCH_SIZE:-512}
QUESTIONER_ROLLOUT_N=${QUESTIONER_ROLLOUT_N:-4}
QUESTIONER_GLOBAL_BATCH_SIZE=${QUESTIONER_GLOBAL_BATCH_SIZE:-4}
QUESTIONER_MICRO_BATCH_UPDATE=${QUESTIONER_MICRO_BATCH_UPDATE:-2}
QUESTIONER_MICRO_BATCH_EXPERIENCE=${QUESTIONER_MICRO_BATCH_EXPERIENCE:-8}
QUESTIONER_VAL_BEFORE_TRAIN=${QUESTIONER_VAL_BEFORE_TRAIN:-false}

# Question generation, labeling, and Base-fit Solver training.
QUESTION_GPU_IDS=${QUESTION_GPU_IDS:-0,1,2,3}
SOLVER_GENERATE_SAMPLES=${SOLVER_GENERATE_SAMPLES:-1000}
SOLVER_MAX_RESPONSE_LENGTH=${SOLVER_MAX_RESPONSE_LENGTH:-4096}
SOLVER_TOTAL_EPOCHS=${SOLVER_TOTAL_EPOCHS:-100}
SOLVER_MAX_STEPS=${SOLVER_MAX_STEPS:-20}
SOLVER_VAL_FREQ=${SOLVER_VAL_FREQ:-4}
SOLVER_MERGE_STEP=${SOLVER_MERGE_STEP:-15}
SOLVER_SAVE_FREQ=${SOLVER_SAVE_FREQ:-5}
SOLVER_SAVE_LIMIT=${SOLVER_SAVE_LIMIT:-3}
SOLVER_LOGGER=${SOLVER_LOGGER:-'["console","wandb"]'}
DATASET_MIN_SCORE=${DATASET_MIN_SCORE:-0.3}
DATASET_MAX_SCORE=${DATASET_MAX_SCORE:-0.8}

# Maximum elements loaded from each tensor at once by the FP32 composer.
TASK_VECTOR_CHUNK_ELEMENTS=${TASK_VECTOR_CHUNK_ELEMENTS:-8000000}
FULL_LOAD_VALIDATE=${FULL_LOAD_VALIDATE:-true}

# RELEX rank-1 trajectory. These checkpoints preserve original R-Zero's step-5 rhythm.
RANK1_HISTORY_STEPS=(5 10 15)
RANK1_TARGET_STEP=${RANK1_TARGET_STEP:-15}
RANK1_PRODUCE_FULL_V1_SIDECAR=${RANK1_PRODUCE_FULL_V1_SIDECAR:-true}
