#!/usr/bin/env bash

RUN_NAME=${RUN_NAME:-qwen3_4b_rzero_v1_v3_epistemic_seed42}
PYTHON_BIN=${PYTHON_BIN:-python}
RZERO_MODEL_ABBR=${RZERO_MODEL_ABBR:-qwen3_4b_rzero_8k_5round}
BASE_MODEL=${BASE_MODEL:-Qwen/Qwen3-4B-Base}

: "${STORAGE_PATH:=/engrfs/project/jiaxinh/jinyuan/R-zero-storage}"
: "${HF_DATASETS_CACHE:=${STORAGE_PATH}/cache/huggingface/datasets}"

V1_DATASET_NAME=${V1_DATASET_NAME:-qwen3_4b_rzero_8k_5round_solver_v1}
V2_DATASET_NAME=${V2_DATASET_NAME:-qwen3_4b_rzero_8k_5round_solver_v2}
V3_DATASET_NAME=${V3_DATASET_NAME:-qwen3_4b_rzero_8k_5round_solver_v3}
V1_EXPECTED_ROWS=${V1_EXPECTED_ROWS:-3920}
V2_EXPECTED_ROWS=${V2_EXPECTED_ROWS:-4653}
V3_EXPECTED_ROWS=${V3_EXPECTED_ROWS:-4547}

SOLVER_V1=${SOLVER_V1:-${STORAGE_PATH}/models/${RZERO_MODEL_ABBR}_solver_v1/global_step_15/actor/huggingface}
SOLVER_V2=${SOLVER_V2:-${STORAGE_PATH}/models/${RZERO_MODEL_ABBR}_solver_v2/global_step_15/actor/huggingface}

EXPERIMENT_SEED=${EXPERIMENT_SEED:-42}
POPULATION_SEED=${POPULATION_SEED:-42}
POPULATION_SIZE=8
SAMPLES_PER_EXPERT=8
EPISTEMIC_SIGMAS=0,0.0001,0.0003,0.001,0.003

GPU_IDS=${GPU_IDS:-0,1,2,3}
GPU_MEMORY_UTILIZATION=${GPU_MEMORY_UTILIZATION:-0.8}
INFERENCE_BATCH_SIZE=${INFERENCE_BATCH_SIZE:-32}
MAX_TOKENS=${MAX_TOKENS:-4096}
TEMPERATURE=${TEMPERATURE:-1.0}
TOP_P=${TOP_P:-1.0}
TOP_K=${TOP_K:-40}

JUDGE_MODEL=${JUDGE_MODEL:-gpt-5.6}
JUDGE_CONCURRENCY=${JUDGE_CONCURRENCY:-4}
HUMAN_REVIEW_SIZE=${HUMAN_REVIEW_SIZE:-75}

ANALYSIS_BOOTSTRAP_SAMPLES=${ANALYSIS_BOOTSTRAP_SAMPLES:-10000}
